Update rust to 1.58 from mainline.

diff --git a/ports/opt-ppc/rust/Pkgfile b/ports/opt-ppc/rust/Pkgfile
--- a/ports/opt-ppc/rust/Pkgfile
+++ b/ports/opt-ppc/rust/Pkgfile
@@ -2,35 +2,25 @@
 # URL: https://www.rust-lang.org/
 # Maintainer: Danny Rawlins, crux at romster dot me
 # Depends on: compiler-rt
-# Optional: sccache ccache
+# Optional: sccache ccache libgit2 lld polly
 
 name=rust
-version=1.53.0
-_date=2021-05-06
-_rustc=1.52.0
-#_cargo=$_rustc
-_cargo=1.54.0
-_llvm=12.0.1
+version=1.58.0
+_date=2021-12-02
+_rustc=1.57.0
+_cargo=$_rustc
 release=1
-	case $(uname -m) in
-		ppc) ARCH=powerpc ;;
-		ppc64) ARCH=powerpc64 ;;
-		*) echo unknown arch!; exit 1 ;;
-	esac
-
 source=(https://static.rust-lang.org/dist/${name}c-$version-src.tar.xz
-	https://static.rust-lang.org/dist/$_date/rust-std-$_rustc-$ARCH-unknown-linux-gnu.tar.xz
-	https://static.rust-lang.org/dist/$_date/rustc-$_rustc-$ARCH-unknown-linux-gnu.tar.xz
-	https://static.rust-lang.org/dist/2021-07-29/cargo-$_cargo-$ARCH-unknown-linux-gnu.tar.xz
-	https://github.com/llvm/llvm-project/releases/download/llvmorg-$_llvm/compiler-rt-$_llvm.src.tar.xz
-	0040-rls-atomics.patch
+	https://static.rust-lang.org/dist/$_date/rust-std-$_rustc-x86_64-unknown-linux-gnu.tar.xz
+	https://static.rust-lang.org/dist/$_date/rustc-$_rustc-x86_64-unknown-linux-gnu.tar.xz
+	https://static.rust-lang.org/dist/$_date/cargo-$_cargo-x86_64-unknown-linux-gnu.tar.xz
 	libexec.patch
-	1.53.0-miri-vergen.patch)
+	0002-compiler-Change-LLVM-targets.patch)
 
 unpack_source() {
 	for file in ${source[@]}; do
 		case ${file##*/} in
-			rustc-${version}-src.tar.xz|compiler-rt-${_llvm}.src.tar.xz)
+			rustc-${version}-src.tar.xz)
 			echo "Unpacking $(get_filename $file)";
 			bsdtar -p -o -C ${SRC} -xf $(get_filename $file) ;;
 		*.tar.xz)
@@ -43,70 +33,99 @@ unpack_source() {
 	done
 }
 
+_check_version() {
+	local ERROR
+	local DATE="$(awk '/^.*"date": / {gsub(/"|,/, "", $2); print $2 }' $SRC/${name}c-$version-src/src/stage0.json)"
+	local RUSTC="$(awk '/^.*"version": / {gsub(/"|,/, "", $2); print $2 }' $SRC/${name}c-$version-src/src/stage0.json)"
+
+	printf '\033[0;32m%s\033[0m\n' "Checking versions for bootstrap compiler.."
+	printf '\033[0;32m%s\033[0m\n' "Got _date = $_date && _rustc = $_rustc"
+
+	if [ "$DATE" != "$_date" ]; then
+		printf '\e[1;31m%-6s\e[m\n' "Error: _date $_date != $DATE"
+		ERROR=1
+	fi
+	if [ "$RUSTC" != "$_rustc" ]; then
+		printf '\e[1;31m%-6s\e[m\n' "Error: _rustc $_rustc != $RUSTC"
+		ERROR=1
+	fi
+
+	[ $ERROR ] && exit 1
+	printf '\033[0;32m%s\033[0m\n' "Versions check out! Proceeding.."
+	unset DATE RUSTC ERROR
+}
+
 build() {
+	_check_version
+
 	cd "${name}c-$version-src"
-	patch -p1 -i $SRC/0040-rls-atomics.patch
 
 	# Patch cargo so credential helpers are in /usr/lib instead of /usr/libexec
 	patch -p1 -i $SRC/libexec.patch
 
-	# https://github.com/rust-lang/rust/issues/84182
-	patch -p1 -i $SRC/1.53.0-miri-vergen.patch
-
-	local ERROR
-	local DATE="$(awk '/^date: / { print $2 }' src/stage0.txt)"
-	local RUSTC="$(awk '/^rustc: / { print $2 }' src/stage0.txt)"
-	if [ "$DATE" != "$_date" ]; then
-		printf "\e[031mError: _date $_date != $DATE\033[0m\n"
-		ERROR=1
-	fi
-	if [ "$RUSTC" != "$_rustc" ]; then
-		printf "\e[031mError: _rustc $_rustc != $RUSTC\033[0m\n"
-		ERROR=1
-	fi
-	[ $ERROR ] && exit 1
-	unset DATE RUSTC ERROR
+	# Use our *-pc-linux-gnu targets, making LTO with clang simpler
+	patch -p1 -i $SRC/0002-compiler-Change-LLVM-targets.patch
 
 cat <<- EOF > $SRC/config.toml
+	changelog-seen = 2
+
 	[llvm]
 	ninja = true
 	link-shared = true
+	@POLLY@
 	@CCACHE@
 
 	[install]
 	prefix = "/usr"
 
 	[rust]
+	# LLVM crashes when passing an object through ThinLTO twice.  This is triggered
+	# when using rust code in cross-language LTO if libstd was built using ThinLTO.
+	# http://blog.llvm.org/2019/09/closing-gap-cross-language-lto-between.html
+	# https://github.com/rust-lang/rust/issues/54872
+	codegen-units-std = 1
+	debuginfo-level-std = 2
+	codegen-tests = false
+
+	description = "CRUX"
 	channel = "stable"
+	parallel-compiler = true
 	rpath = false
+	optimize = true
+	@LLD@
 
 	[build]
-	target = ["$ARCH-unknown-linux-gnu"]
-	tools = ["cargo", "rls", "clippy", "miri", "rustfmt", "analysis", "src"]
+	target = ["x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu"]
+	tools = ["cargo", "rls", "clippy", "rustfmt", "analysis", "src", "rust-demangler"]
 	docs = false
 	extended = true
-	sanitizers = false
+	sanitizers = true
 	profiler = true
 	vendor = true
 	python = "/usr/bin/python3"
 	@CARGO@
 	@RUST@
+	@RUSTFMT@
 
-	[target.$ARCH-unknown-linux-gnu]
+	[target.x86_64-unknown-linux-gnu]
 	llvm-config = "/usr/bin/llvm-config"
+	llvm-filecheck = "/usr/bin/FileCheck"
 EOF
 
 	if [ -e '/usr/bin/rustc' ]; then
-		if [ -z "$(/usr/bin/ldd /usr/bin/rustc | egrep '.*libLLVM.*.so => not found')" ]; then
+		if [[ -z "$(/usr/bin/ldd /usr/bin/rustc | egrep '.*libLLVM.*.so => not found')" && \
+			-z "$(/usr/bin/ldd /usr/bin/cargo | egrep 'libgit2.so.* => not found')" ]]; then
+
 			sed	-e 's|@CARGO@|cargo = "/usr/bin/cargo"|' \
 				-e 's|@RUST@|rustc = "/usr/bin/rustc"|' \
+				-e 's|@RUSTFMT@|rustfmt = "/usr/bin/rustfmt"|' \
 				-i $SRC/config.toml
 		else
-			sed -e 's|@CARGO@||' -e 's|@RUST@||' -i $SRC/config.toml
-			printf "\e[031mllvm broken symlink detected, not using system rust to bootstrap\033[0m\n"
+			sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/config.toml
+			printf "\e[031mShared library missing, not using system rust to bootstrap.\033[0m\n"
 		fi
 	else
-		sed -e 's|@CARGO@||' -e 's|@RUST@||' -i $SRC/config.toml
+		sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/config.toml
 	fi
 
 	if [ -e '/usr/bin/ccache' ]; then
@@ -115,18 +134,26 @@ EOF
 		sed -e 's|@CCACHE@||' -i $SRC/config.toml
 	fi
 
+	prt-get isinst lld && sed -e 's|@LLD@|use-lld = true|' -i $SRC/config.toml || sed -e 's|@LLD@||' -i $SRC/config.toml
+	prt-get isinst polly && sed -e 's|@POLLY@|polly = true|' -i $SRC/config.toml || sed -e 's|@POLLY@||' -i $SRC/config.toml
+
 	cat $SRC/config.toml
 
 	mkdir "$PKGMK_SOURCE_DIR/rust" || true
 	export CARGO_HOME="$PKGMK_SOURCE_DIR/rust"
 
-        if [ -e '/usr/bin/sccache' ]; then
-                export RUSTC_WRAPPER='/usr/bin/sccache'
-                export SCCACHE_IDLE_TIMEOUT='1500'
-        fi
+	if [ -e '/usr/bin/sccache' ]; then
+		export RUSTC_WRAPPER='/usr/bin/sccache'
+		export SCCACHE_IDLE_TIMEOUT='1500'
+	fi
 
+	#error: field is never read: `id`
+	#   --> src/bootstrap/lib.rs:280:5
+	#   = note: `-D dead-code` implied by `-D warnings`
+	export RUSTFLAGS+=' -A dead_code'
+
+	export LIBGIT2_NO_PKG_CONFIG=1
 	export RUST_BACKTRACE=full
-	export RUST_COMPILER_RT_ROOT="$SRC/compiler-rt-$_llvm.src"
 	/usr/bin/python3 ./x.py build --config="${SRC}"/config.toml -j ${JOBS-1}
 	DESTDIR=$PKG /usr/bin/python3 ./x.py --config="${SRC}"/config.toml install
 
@@ -149,5 +176,5 @@ EOF
 	done < <(find "$PKG/usr/lib/rustlib"  -path '*/analysis/*.json' -print0)
 
 	install -d $PKG/etc/revdep.d
-	#echo "/usr/lib/rustlib/i686-unknown-linux-gnu/lib" > $PKG/etc/revdep.d/$name
+	echo "/usr/lib/rustlib/i686-unknown-linux-gnu/lib" > $PKG/etc/revdep.d/$name
 }
