Initial changes to core files for CRUX PPC 3.6

diff --git a/ports/core-ppc/gcc/Pkgfile b/ports/core-ppc/gcc/Pkgfile
--- a/ports/core-ppc/gcc/Pkgfile
+++ b/ports/core-ppc/gcc/Pkgfile
@@ -1,10 +1,12 @@
 # Description: The GNU Compiler Collection
 # URL:         http://gcc.gnu.org
-# Maintainer:  CRUX System Team, core-ports at crux dot nu
+# Maintainer:  cruxppc at gmail dot com
 # Depends on:  zlib libmpc zstd
 
 name=gcc
 version=10.2.0
+# 10.2.0 on ppc fails to build some packages.  Downrev to 9.3.0 for now at least.
+version=9.3.0
 release=1
 source=(ftp://gcc.gnu.org/pub/gcc/releases/gcc-$version/$name-$version.tar.xz \
 	$name-nocheck-fixincludes.patch $name-4.7.3-multilib-dirs.patch)
@@ -12,7 +14,7 @@ source=(ftp://gcc.gnu.org/pub/gcc/releases/gcc-$version/$name-$version.tar.xz \
 
 build() {
     patch -d $name-$version -p1 -i $SRC/$name-nocheck-fixincludes.patch
-    patch -d $name-$version -p1 -i $SRC/$name-4.7.3-multilib-dirs.patch
+#    patch -d $name-$version -p1 -i $SRC/$name-4.7.3-multilib-dirs.patch
 
     ##glibc 2.31 issue
     #sed -e '1161 s|^|//|' \
@@ -30,11 +32,20 @@ build() {
                                 --disable-nls \
                                 --with-x=no \
                                 --with-system-zlib \
-                                --enable-multilib \
+                                --without-isl \
+                                --disable-multilib \
+                                --disable-bootstrap \
 				--enable-default-pie \
 				--enable-default-ssp \
-                                --with-pkgversion="CRUX-x86_64-multilib"
-    make bootstrap
+				--enable-secure-plt \
+                                --with-pkgversion="CRUX-PPC"
+    #make bootstrap
+    make
+
+    #ulimit -s 32768
+    #make -k check || true
+    #../contrib/test_summary
+
     make -j1 DESTDIR=$PKG install
 
     install -d $PKG/lib
@@ -47,10 +58,27 @@ build() {
     rm -r $PKG/usr/bin/*-linux-gnu-*
     rm -r $PKG/usr/lib/gcc/*/$version/{install-tools,include-fixed} 
 
-    for D in lib{,32}; do
-        install -d -m 0755 $PKG/usr/share/gdb/auto-load/usr/${D}
-        mv $PKG/usr/${D}/libstdc++.so.*-gdb.py $PKG/usr/share/gdb/auto-load/usr/${D}
-    done
+    case $(uname -m) in
+        ppc) 
+            install -d -m 0755 $PKG/usr/share/gdb/auto-load/usr/lib
+            mv $PKG/usr/lib/libstdc++.so.*-gdb.py $PKG/usr/share/gdb/auto-load/usr/lib
+            sed -i "s|-L$SRC[^ ]* ||g" $PKG/usr/lib/{libstdc++.la,libsupc++.la} 
+        ;;
+   
+        ppc64) 
+            install -d -m 0755 $PKG/usr/share/gdb/auto-load/usr/lib64
+            mv $PKG/usr/lib64/libstdc++.so.*-gdb.py $PKG/usr/share/gdb/auto-load/usr/lib64
+            sed -i "s|-L$SRC[^ ]* ||g" $PKG/usr/lib64/{libstdc++.la,libsupc++.la}
+        ;;
+    esac
 
-    sed -i "s|-L$SRC[^ ]* ||g" $PKG/usr/lib{,32}/{libstdc++.la,libsupc++.la}
+#    for D in lib{,32}; do
+#        install -d -m 0755 $PKG/usr/share/gdb/auto-load/usr/${D}
+#        mv $PKG/usr/${D}/libstdc++.so.*-gdb.py $PKG/usr/share/gdb/auto-load/usr/${D}
+#    done
+
+#    case $(uname -m) in
+#        ppc) sed -i "s|-L$SRC[^ ]* ||g" $PKG/usr/lib/{libstdc++.la,libsupc++.la} ;;
+#        ppc64) sed -i "s|-L$SRC[^ ]* ||g" $PKG/usr/lib64/{libstdc++.la,libsupc++.la}
+#    esac
 }
